---
name: Catalyst-Plugin-Cache
version: 0.01
author: []
abstract: Flexible caching support for Catalyst.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.7
  Storable: 0
  Task::Weaken: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  perl: 5.8.1
provides:
  Catalyst::Plugin::Cache:
    file: lib/Catalyst/Plugin/Cache.pm
    version: 0.01
  Catalyst::Plugin::Cache::Backend:
    file: lib/Catalyst/Plugin/Cache/Backend.pm
  Catalyst::Plugin::Cache::Backend::Memory:
    file: lib/Catalyst/Plugin/Cache/Backend/Memory.pm
  Catalyst::Plugin::Cache::Choose::KeyRegexes:
    file: lib/Catalyst/Plugin/Cache/Choose/KeyRegexes.pm
  Catalyst::Plugin::Cache::Curried:
    file: lib/Catalyst/Plugin/Cache/Curried.pm
  Catalyst::Plugin::Cache::Store::Memory:
    file: lib/Catalyst/Plugin/Cache/Store/Memory.pm
generated_by: Module::Build version 0.2801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
