# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Cache
version:      0.02
version_from: lib/Catalyst/Plugin/Cache.pm
installdirs:  site
requires:
    Catalyst:                      5.7
    Storable:                      0
    Task::Weaken:                  0
    Test::Deep:                    0
    Test::Exception:               0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
