--- #YAML:1.0
name:               Catalyst-Plugin-Cache
version:            0.08
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:         5.7
    MRO::Compat:      0
    ok:               0
    Storable:         0
    Task::Weaken:     0
    Test::Deep:       0
    Test::Exception:  0
    Test::More:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
